name: Issue assignment

on:
  issue_comment:
    types: [created, edited]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: edwinRNDR/pick-me@v0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}